### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by Anujraval24** [Anujraval24/BlockChain#1]
![workspace - java - blockchain demo_src_block java - eclipse 21-oct-17 5_09_57 pm](https://user-images.githubusercontent.com/17050077/31851425-0c2c35ba-b683-11e7-86ee-288bba262d36.png)
![workspace - java - blockchain demo_src_block java - eclipse 21-oct-17 5_10_05 pm](https://user-images.githubusercontent.com/17050077/31851426-0c67d462-b683-11e7-99f5-b6cdefca0606.png)

**Comment by huanleyuan** [comment]
simple,sometimes naieve

**Comment by Anujraval24** [comment]
sureeee
